

[features]
resolution = true
skip-lint = false

[programs.localnet]
djinn_market = "DSsD8neGhs9Ae9gVuWjmUfVckEvw36GamNboxWQCNqKQ"

[programs.devnet]
djinn_market = "9xXGnGG4hxwC4XTHavmy5BWAdb8MC2VJtTDMW9FfkGbg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/benjaminfuentes/Djinn-pmarket/deploy-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[build]
bootloader = "https://github.com/coral-xyz/sealevel-tools/releases/download/v0.3.0/sealevel-tools.tar.gz"