[toolchain]
package_manager = "npm"
solana_version = "1.18.20"

[features]
resolution = true
skip-lint = false

[programs.localnet]
djinn_market = "DSsD8neGhs9Ae9gVuWjmUfVckEvw36GamNboxWQCNqKQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[build]
bootloader = "https://github.com/coral-xyz/sealevel-tools/releases/download/v0.3.0/sealevel-tools.tar.gz"
