

[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.28.0"
solana_version = "1.18.20"

[programs.localnet]
djinn_market = "EkWbgwnLtY76MYzKZPWCz6xBwkrScktK6cpgXQb4GdU6"

[programs.devnet]
djinn_market = "EkWbgwnLtY76MYzKZPWCz6xBwkrScktK6cpgXQb4GdU6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[build]
bootloader = "https://github.com/coral-xyz/sealevel-tools/releases/download/v0.3.0/sealevel-tools.tar.gz"

[test.validator]
startup_wait = 400000